services:
  web:
    build: .
    ports:
      - "5001:5001"
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://mongo:27017/jungdry
    depends_on:
      - mongo
    volumes:
      - ./static:/app/static
      - ./templates:/app/templates

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: